baseurl: https://svfcode.github.io
languageCode: en-us
theme: hugo-theme-stack
paginate: 8
title: My blog

permalinks:
    post: /p/:slug/
    page: /:slug/

DefaultContentLanguage: en
languages:
    en:
        languageName: en
        title: Blog
        description: php, js, db, linux, etc.
        weight: 2
    ru:
        languageName: ru
        title: Блог
        description: php, js, db, linux, etc.
        weight: 1

params:
    sidebar:
        # emoji: 🍥
        subtitle: php, js, db, linux, etc.
        avatar:
            enabled: true
            local: true
            src: img/avatar.jpg

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc