baseurl: https://svfcode.github.io
languageCode: en-us
theme: hugo-theme-stack
paginate: 8
title: My blog

permalinks:
    post: /p/:slug/
    page: /:slug/

DefaultContentLanguage: ru
languages:
    en:
        languageName: en
        title: Blog
        description: go, js, php, linux, db, etc.
        weight: 2
    ru:
        languageName: ru
        title: Блог
        description: go, js, php, linux, db, etc.
        weight: 1

params:
    comments:
        enabled: true
        provider: disqus
        disqusShortname: svfcode

    sidebar:
        avatar: false

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

disqusShortname: svfcode
